#!/usr/bin/env bash
# kb-index.sh — rebuild .kb/_index.json from KB entry frontmatter.
#
# The index is a flat JSON array of entry summaries — title, type, tags,
# applies_to, etc. — used by /kb facet queries (`kb-search.sh --facet ...`)
# to filter entries by structured metadata without iterating the whole
# tree on every query.
#
# Generated by /research after every KB write. Gitignored — per-machine
# cache, regenerated cheaply from frontmatter.
#
# Schema (current: schema_version 1):
# {
#   "schema_version": 1,
#   "generated_at": "<ISO-8601 UTC>",
#   "kb_root": ".kb",
#   "entry_count": N,
#   "entries": [
#     {
#       "path": ".kb/algorithms/encryption/three-level-keys.md",
#       "title": "Three-level key hierarchy",
#       "type": "research",
#       "topic": "algorithms",                # derived from path
#       "category": "encryption",             # derived from path
#       "tags": ["encryption", "key-hierarchy"],
#       "applies_to": ["src/main/auth/**"],
#       "domain": null,                       # adversarial-finding only
#       "severity": null,                     # adversarial-finding only
#       "domains": [],                        # feature-footprint only
#       "constructs": [],                     # feature-footprint only
#       "research_status": "stable",
#       "confidence": "medium",
#       "last_researched": "2026-05-09",
#       "related": [],
#       "decision_refs": []
#     },
#     ...
#   ]
# }
#
# Excluded from the index:
#   - .kb/CLAUDE.md and per-topic/category index files
#   - .kb/_refs/* (schema and convention docs, not entries)
#   - .kb/_archive* (older entries archived from Recently Added)
#   - <subject>-detail.md companion files (they have type:detail-companion
#     and are surfaced via the parent's @./ include — not standalone
#     entries from the search PoV)
#
# Usage:
#   bash kb-index.sh [--kb-root .kb] [--out .kb/_index.json]
#
# Atomic write via <out>.tmp.<pid> + rename — concurrent /kb queries can
# read the index without seeing a torn write.

set -euo pipefail

KB_ROOT=".kb"
OUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --kb-root) KB_ROOT="${2:-}"; shift 2 ;;
        --out)     OUT="${2:-}";     shift 2 ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" >&2
            exit 0
            ;;
        *)
            echo "unknown arg: $1" >&2
            exit 2
            ;;
    esac
done

[[ -z "$OUT" ]] && OUT="$KB_ROOT/_index.json"

if [[ ! -d "$KB_ROOT" ]]; then
    echo "ERROR: KB root does not exist: $KB_ROOT" >&2
    exit 2
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 required for kb-index.sh" >&2
    exit 2
fi

# Hand the heavy lifting (YAML-ish frontmatter → JSON) to python3. We pass
# the KB root and output path; python writes to a tmp file, then bash
# renames atomically.

TMP="${OUT}.tmp.$$"

python3 - "$KB_ROOT" "$TMP" <<'PYEOF'
"""Rebuild the KB index from entry frontmatter.

Tolerates both YAML forms found in vallorcine entries:
  * inline scalar:   `title: "<value>"`
  * inline list:     `applies_to: ["a", "b"]`
  * block list:      `applies_to:\n  - a\n  - b`

Does NOT use a real YAML parser (no PyYAML dep) — frontmatter is
constrained enough that grep+regex is sufficient. The schema check
in `kb_refs/frontmatter.md` rejects exotic YAML so the index never
sees ambiguous shapes in practice.
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

kb_root = Path(sys.argv[1])
out_tmp = Path(sys.argv[2])

EXCLUDED_NAMES = {"CLAUDE.md"}
EXCLUDED_DIRS = {"_refs"}
EXCLUDED_PREFIXES = ("_archive",)

SCALAR_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*?)\s*$")
INLINE_LIST_RE = re.compile(r"^\[(.*)\]$")
BLOCK_ITEM_RE = re.compile(r"^\s*-\s+(.*?)\s*$")


def strip_quotes(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return s[1:-1]
    return s


def parse_frontmatter(path: Path) -> dict | None:
    """Return the frontmatter dict, or None if no frontmatter block."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            line = f.readline()
            if line.strip() != "---":
                return None
            block = []
            for line in f:
                if line.strip() == "---":
                    break
                block.append(line.rstrip("\n"))
            else:
                return None  # no closing ---
    except OSError:
        return None

    out: dict[str, object] = {}
    i = 0
    while i < len(block):
        line = block[i]
        m = SCALAR_RE.match(line)
        if not m:
            i += 1
            continue
        key, value = m.group(1), m.group(2)

        if value == "":
            # Block-form list. Consume subsequent indented `- ...` lines.
            items: list[str] = []
            j = i + 1
            while j < len(block):
                bm = BLOCK_ITEM_RE.match(block[j])
                if bm:
                    items.append(strip_quotes(bm.group(1)))
                    j += 1
                elif block[j].strip() == "" or block[j].startswith(" "):
                    # Blank or indented continuation that isn't a list item — stop.
                    break
                else:
                    break
            out[key] = items
            i = j
            continue

        inline = INLINE_LIST_RE.match(value)
        if inline is not None:
            inner = inline.group(1).strip()
            if inner == "":
                out[key] = []
            else:
                out[key] = [strip_quotes(p) for p in inner.split(",") if p.strip()]
            i += 1
            continue

        # Plain scalar.
        out[key] = strip_quotes(value)
        i += 1

    return out


def is_excluded(rel: Path) -> bool:
    parts = rel.parts
    if rel.name in EXCLUDED_NAMES:
        return True
    for part in parts:
        if part in EXCLUDED_DIRS:
            return True
        if any(part.startswith(p) for p in EXCLUDED_PREFIXES):
            return True
    return False


entries = []

for md in sorted(kb_root.rglob("*.md")):
    rel = md.relative_to(kb_root)
    if is_excluded(rel):
        continue
    fm = parse_frontmatter(md)
    if fm is None:
        # Files without frontmatter aren't entries (likely an in-progress
        # draft). Skip silently — `/curate` schema-drift will surface them.
        continue

    entry_type = fm.get("type") or "research"
    if entry_type == "detail-companion":
        # Companions are surfaced via parent @./ include, not as standalone
        # entries. They have their own validation in /curate but don't
        # belong in the search index.
        continue

    parts = rel.parts
    topic = parts[0] if len(parts) >= 2 else ""
    category = parts[1] if len(parts) >= 3 else ""

    def field(name: str, default=None):
        v = fm.get(name)
        return v if v is not None else default

    def list_field(name: str) -> list:
        v = fm.get(name)
        if v is None:
            return []
        if isinstance(v, list):
            return v
        # Scalar fallback (e.g. tags: foo) — wrap in single-element list.
        return [v]

    entries.append({
        "path": str(md.as_posix()),
        "title": field("title", ""),
        "type": entry_type,
        "topic": topic,
        "category": category,
        "tags": list_field("tags"),
        "applies_to": list_field("applies_to"),
        "domain": field("domain"),
        "severity": field("severity"),
        "domains": list_field("domains"),
        "constructs": list_field("constructs"),
        "research_status": field("research_status"),
        "confidence": field("confidence"),
        "last_researched": field("last_researched"),
        "related": list_field("related"),
        "decision_refs": list_field("decision_refs"),
        "spec_refs": list_field("spec_refs"),
    })

doc = {
    "schema_version": 1,
    "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "kb_root": str(kb_root.as_posix()),
    "entry_count": len(entries),
    "entries": entries,
}

out_tmp.parent.mkdir(parents=True, exist_ok=True)
with out_tmp.open("w", encoding="utf-8") as f:
    json.dump(doc, f, indent=2, ensure_ascii=False)
PYEOF

mv "$TMP" "$OUT"

# Brief stdout summary so the caller can see what landed.
ENTRY_COUNT="$(python3 -c '
import json, sys
try:
    print(json.load(open(sys.argv[1])).get("entry_count", 0))
except Exception:
    print(0)
' "$OUT")"
echo "[kb-index] wrote $OUT ($ENTRY_COUNT entries)"
